insert into public.admin_roles (key, name, permissions) values
  ('owner','Owner',array['config:read','config:write','tools:read','tools:write','users:read','users:write','logs:read','system:write']::public.admin_permission[]),
  ('administrator','Administrator',array['config:read','config:write','tools:read','tools:write','logs:read']::public.admin_permission[])
on conflict (key) do nothing;

insert into public.tool_categories (key,name,description,order_index) values
  ('financial','Financial','Financial calculators and management tools.',10),
  ('tax','Tax','Tax calculators and compliance tools.',20),
  ('hr','HR','Human resources and payroll tools.',30),
  ('import-export','Import & Export','Foreign trade and operational tools.',40),
  ('ai','AI','Future AI-powered tools.',50)
on conflict (key) do nothing;

insert into public.tools (category_id,key,name,description,status,feature_flags) select id,'roi','ROI','Calculadora de retorno sobre investimento.','active','{"enabled":true}'::jsonb from public.tool_categories where key='financial' on conflict (key) do nothing;
insert into public.tools (category_id,key,name,description,status,feature_flags) select id,'markup','Markup','Calculadora de preço de venda por markup.','active','{"enabled":true}'::jsonb from public.tool_categories where key='financial' on conflict (key) do nothing;
insert into public.tools (category_id,key,name,description,status,feature_flags) select id,'simples-nacional','Simples Nacional','Calculadora de DAS do Simples Nacional.','active','{"enabled":true}'::jsonb from public.tool_categories where key='tax' on conflict (key) do nothing;

insert into public.system_settings (settings) values ('{"platform_name":"Nicemp","locale":"pt-BR","feature_flags":{"roi":true,"markup":true,"simples_nacional":true,"admin_configuration":true},"validation_messages":{"required":"Campo obrigatório.","invalid_number":"Informe um número válido."}}'::jsonb);
insert into public.financial_settings (settings) values ('{"default_currency":"BRL","roi":{"investment":{"key":"investment","min":0,"max":null,"inclusive_min":false,"inclusive_max":true,"message":"Informe um valor de investimento válido maior que zero."},"return_value":{"key":"return_value","min":0,"max":null,"inclusive_min":true,"inclusive_max":true,"message":"Informe um retorno válido não negativo."},"labels":{"investment":"Investimento","return_value":"Retorno"},"help_texts":{"investment":"Valor total investido.","return_value":"Valor total retornado pelo investimento."}},"markup":{"cost":{"key":"cost","min":0,"max":null,"inclusive_min":false,"inclusive_max":true,"message":"Informe um custo válido maior que zero."},"expenses_percent":{"key":"expenses_percent","min":0,"max":100,"inclusive_min":true,"inclusive_max":false,"message":"Informe um percentual de despesas válido."},"margin_percent":{"key":"margin_percent","min":0,"max":100,"inclusive_min":false,"inclusive_max":false,"message":"Informe uma margem de lucro válida maior que zero."},"combined_percent_limit":{"key":"combined_percent_limit","value":100,"message":"A soma de despesas e margem não pode atingir ou ultrapassar 100%."},"labels":{"cost":"Custo","expenses_percent":"Despesas","margin_percent":"Margem"},"help_texts":{"cost":"Custo unitário do produto ou serviço.","expenses_percent":"Percentual de despesas sobre o preço de venda.","margin_percent":"Percentual de lucro esperado."}}}'::jsonb);
insert into public.hr_settings (settings) values ('{"payroll":{"enabled":false,"validation_messages":{},"future_integrations":{}}}'::jsonb);
insert into public.import_settings (settings) values ('{"allowed_extensions":["csv","xlsx","xls"],"max_file_size_mb":20,"validation_messages":{"invalid_extension":"Formato de arquivo não permitido.","max_size":"Arquivo acima do tamanho máximo permitido."},"future_integrations":{}}'::jsonb);
insert into public.export_settings (settings) values ('{"allowed_formats":["csv","xlsx","pdf"],"default_format":"xlsx","validation_messages":{},"future_integrations":{}}'::jsonb);
insert into public.tax_settings (settings) values ('{"simples_nacional":{"max_rbt12":4800000,"monthly_revenue":{"key":"monthly_revenue","min":0,"max":null,"inclusive_min":false,"inclusive_max":true,"message":"A receita bruta do mês atual deve ser maior que zero."},"rbt12":{"key":"rbt12","min":0,"max":4800000,"inclusive_min":false,"inclusive_max":true,"message":"O faturamento acumulado dos últimos 12 meses deve estar dentro do limite do Simples Nacional."},"brackets":[],"annex_descriptions":{"I":"Comércio","II":"Indústria","III":"Serviços","IV":"Serviços com incidência específica","V":"Serviços sujeitos ao Fator R"},"states":["AC","AL","AP","AM","BA","CE","DF","ES","GO","MA","MT","MS","MG","PA","PB","PR","PE","PI","RJ","RN","RS","RO","RR","SC","SP","SE","TO"],"legal_texts":{"formula":"Alíquota Efetiva = ((RBT12 × Alíquota Nominal) − Parcela a Deduzir) ÷ RBT12.","das":"DAS = Receita Bruta do Mês × Alíquota Efetiva."},"validation_messages":{"limit_exceeded":"O RBT12 ultrapassa o limite máximo do Simples Nacional.","invalid_annex":"Informe um anexo válido."}}}'::jsonb);

insert into public.tax_regimes (key,name,description) values ('simples_nacional','Simples Nacional','Regime tributário simplificado para micro e pequenas empresas.') on conflict (key) do nothing;
insert into public.states (code,name) values ('AC','Acre'),('AL','Alagoas'),('AP','Amapá'),('AM','Amazonas'),('BA','Bahia'),('CE','Ceará'),('DF','Distrito Federal'),('ES','Espírito Santo'),('GO','Goiás'),('MA','Maranhão'),('MT','Mato Grosso'),('MS','Mato Grosso do Sul'),('MG','Minas Gerais'),('PA','Pará'),('PB','Paraíba'),('PR','Paraná'),('PE','Pernambuco'),('PI','Piauí'),('RJ','Rio de Janeiro'),('RN','Rio Grande do Norte'),('RS','Rio Grande do Sul'),('RO','Rondônia'),('RR','Roraima'),('SC','Santa Catarina'),('SP','São Paulo'),('SE','Sergipe'),('TO','Tocantins') on conflict (code) do nothing;
