import { z } from "zod";

const rangeRuleSchema = z.object({ key: z.string().min(1), min: z.number().nullable(), max: z.number().nullable(), inclusive_min: z.boolean(), inclusive_max: z.boolean(), message: z.string().min(1) });
const limitRuleSchema = z.object({ key: z.string().min(1), value: z.number(), message: z.string().min(1) });
const taxBracketSchema = z.object({ regime: z.string().min(1), annex: z.enum(["I", "II", "III", "IV", "V"]), bracket: z.number().int().positive(), min_revenue: z.number().min(0), max_revenue: z.number().positive(), nominal_rate: z.number().min(0), deduction_amount: z.number().min(0) });
export const generalConfigSchema = z.object({ platform_name: z.string().min(1), locale: z.literal("pt-BR"), feature_flags: z.record(z.boolean()), validation_messages: z.record(z.string()) });
export const financialConfigSchema = z.object({ default_currency: z.literal("BRL"), roi: z.object({ investment: rangeRuleSchema, return_value: rangeRuleSchema, labels: z.record(z.string()), help_texts: z.record(z.string()) }), markup: z.object({ cost: rangeRuleSchema, expenses_percent: rangeRuleSchema, margin_percent: rangeRuleSchema, combined_percent_limit: limitRuleSchema, labels: z.record(z.string()), help_texts: z.record(z.string()) }) });
export const taxConfigSchema = z.object({ simples_nacional: z.object({ max_rbt12: z.number().positive(), monthly_revenue: rangeRuleSchema, rbt12: rangeRuleSchema, brackets: z.array(taxBracketSchema).min(1), annex_descriptions: z.record(z.string()), states: z.array(z.string().length(2)), legal_texts: z.record(z.string()), validation_messages: z.record(z.string()) }) });
export const hrConfigSchema = z.object({ payroll: z.object({ enabled: z.boolean(), validation_messages: z.record(z.string()), future_integrations: z.record(z.string()) }) });
export const importConfigSchema = z.object({ allowed_extensions: z.array(z.string().min(1)), max_file_size_mb: z.number().positive(), validation_messages: z.record(z.string()), future_integrations: z.record(z.string()) });
export const exportConfigSchema = z.object({ allowed_formats: z.array(z.string().min(1)), default_format: z.string().min(1), validation_messages: z.record(z.string()), future_integrations: z.record(z.string()) });
export const seoConfigSchema = z.object({ id: z.string().uuid(), created_at: z.string(), updated_at: z.string(), active: z.boolean(), version: z.number().int().positive(), effective_date: z.string(), created_by: z.string().uuid().nullable(), updated_by: z.string().uuid().nullable(), tool_key: z.string().nullable(), route: z.string().min(1), title: z.string().min(1), meta_description: z.string().min(1), canonical: z.string().nullable(), open_graph: z.unknown(), twitter_card: z.unknown(), faq_schema: z.unknown(), software_application_schema: z.unknown(), json_ld: z.unknown() });
export const moduleSchemas = { general: generalConfigSchema, financial: financialConfigSchema, tax: taxConfigSchema, hr: hrConfigSchema, import: importConfigSchema, export: exportConfigSchema, seo: z.array(seoConfigSchema) };
export function validateRange(value: number, rule: z.infer<typeof rangeRuleSchema>): string | null { if (rule.min !== null) { const valid = rule.inclusive_min ? value >= rule.min : value > rule.min; if (!valid) return rule.message; } if (rule.max !== null) { const valid = rule.inclusive_max ? value <= rule.max : value < rule.max; if (!valid) return rule.message; } return null; }
