create extension if not exists "pgcrypto";

create type public.config_module as enum ('general','financial','tax','hr','import','export','seo');
create type public.tool_status_type as enum ('draft','active','inactive','archived');
create type public.admin_permission as enum ('config:read','config:write','tools:read','tools:write','users:read','users:write','logs:read','system:write');

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'); $$;

create table public.admin_roles (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), active boolean not null default true, version integer not null default 1, effective_date timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), key text not null unique, name text not null, permissions public.admin_permission[] not null default '{}');
create table public.tool_categories (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), active boolean not null default true, version integer not null default 1, effective_date timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), key text not null unique, name text not null, description text not null default '', order_index integer not null default 0);
create table public.tools (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), active boolean not null default true, version integer not null default 1, effective_date timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), category_id uuid references public.tool_categories(id), key text not null unique, name text not null, description text not null default '', status public.tool_status_type not null default 'draft', feature_flags jsonb not null default '{}');
create table public.tool_status (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), active boolean not null default true, version integer not null default 1, effective_date timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), tool_id uuid not null references public.tools(id) on delete cascade, status public.tool_status_type not null, reason text);
create table public.tool_settings (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), active boolean not null default true, version integer not null default 1, effective_date timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), tool_key text not null references public.tools(key), module_key public.config_module not null, settings jsonb not null default '{}');
create table public.tool_fields (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), active boolean not null default true, version integer not null default 1, effective_date timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), tool_id uuid not null references public.tools(id) on delete cascade, key text not null, label text not null, type text not null, required boolean not null default false, default_value jsonb, validation jsonb not null default '{}', help_text text, order_index integer not null default 0, unique (tool_id,key,version));
create table public.tool_examples (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), active boolean not null default true, version integer not null default 1, effective_date timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), tool_id uuid not null references public.tools(id) on delete cascade, title text not null, description text not null, input jsonb not null default '{}', output jsonb not null default '{}', order_index integer not null default 0);
create table public.tool_faq (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), active boolean not null default true, version integer not null default 1, effective_date timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), tool_id uuid not null references public.tools(id) on delete cascade, question text not null, answer text not null, order_index integer not null default 0);
create table public.tool_seo (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), active boolean not null default true, version integer not null default 1, effective_date timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), tool_key text references public.tools(key), route text not null, title text not null, meta_description text not null, canonical text, open_graph jsonb not null default '{}', twitter_card jsonb not null default '{}', faq_schema jsonb not null default '[]', software_application_schema jsonb not null default '{}', json_ld jsonb not null default '{}');

create table public.system_settings (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), active boolean not null default true, version integer not null default 1, effective_date timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), settings jsonb not null default '{}');
create table public.financial_settings (like public.system_settings including all);
create table public.tax_settings (like public.system_settings including all);
create table public.hr_settings (like public.system_settings including all);
create table public.import_settings (like public.system_settings including all);
create table public.export_settings (like public.system_settings including all);

create table public.tax_regimes (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), active boolean not null default true, version integer not null default 1, effective_date timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), key text not null unique, name text not null, description text not null default '');
create table public.tax_brackets (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), active boolean not null default true, version integer not null default 1, effective_date timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), regime_key text not null references public.tax_regimes(key), annex text not null, bracket integer not null, min_revenue numeric(14,2) not null, max_revenue numeric(14,2) not null, nominal_rate numeric(10,6) not null, deduction_amount numeric(14,2) not null);
create table public.tax_rates (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), active boolean not null default true, version integer not null default 1, effective_date timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), key text not null, label text not null, rate numeric(10,6) not null, metadata jsonb not null default '{}');
create table public.tax_limits (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), active boolean not null default true, version integer not null default 1, effective_date timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), key text not null, value numeric(14,2) not null, message text not null);
create table public.tax_deductions (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), active boolean not null default true, version integer not null default 1, effective_date timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), key text not null, amount numeric(14,2) not null, metadata jsonb not null default '{}');
create table public.tax_factor_r (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), active boolean not null default true, version integer not null default 1, effective_date timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), threshold numeric(10,6) not null, source_annex text not null, target_annex text not null, legal_text text not null default '');
create table public.states (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), active boolean not null default true, version integer not null default 1, effective_date timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), code char(2) not null unique, name text not null);
create table public.cities (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), active boolean not null default true, version integer not null default 1, effective_date timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), state_id uuid not null references public.states(id), ibge_code text not null unique, name text not null);
create table public.cnae (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), active boolean not null default true, version integer not null default 1, effective_date timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), code text not null unique, description text not null, annex text, metadata jsonb not null default '{}');
create table public.audit_logs (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), active boolean not null default true, version integer not null default 1, effective_date timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), actor_id uuid references auth.users(id), action text not null, entity_table text not null, entity_id uuid, before_value jsonb, after_value jsonb, metadata jsonb not null default '{}');
create table public.config_versions (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), active boolean not null default true, version integer not null default 1, effective_date timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), module_key public.config_module not null, entity_key text not null, entity_id uuid, config jsonb not null, change_reason text, rollback_of uuid references public.config_versions(id));

create index tools_key_active_idx on public.tools(key,active); create index tool_settings_tool_module_idx on public.tool_settings(tool_key,module_key,active); create index tool_fields_tool_idx on public.tool_fields(tool_id,active,order_index); create index tool_seo_route_idx on public.tool_seo(route,active); create index config_versions_module_idx on public.config_versions(module_key,entity_key,created_at desc); create index audit_logs_actor_idx on public.audit_logs(actor_id,created_at desc); create index tax_brackets_lookup_idx on public.tax_brackets(regime_key,annex,min_revenue,max_revenue,active); create index states_code_idx on public.states(code); create index cities_state_idx on public.cities(state_id,name); create index cnae_code_idx on public.cnae(code);

do $$ declare table_name text; begin foreach table_name in array array['admin_roles','tool_categories','tools','tool_status','tool_settings','tool_fields','tool_examples','tool_faq','tool_seo','system_settings','financial_settings','tax_settings','tax_regimes','tax_brackets','tax_rates','tax_limits','tax_deductions','tax_factor_r','states','cities','cnae','hr_settings','import_settings','export_settings','audit_logs','config_versions'] loop execute format('create trigger %I before update on public.%I for each row execute function public.set_updated_at()', table_name || '_updated_at', table_name); execute format('alter table public.%I enable row level security', table_name); end loop; end $$;

do $$ declare table_name text; begin foreach table_name in array array['tool_categories','tools','tool_settings','tool_fields','tool_examples','tool_faq','tool_seo','system_settings','financial_settings','tax_settings','tax_regimes','tax_brackets','tax_rates','tax_limits','tax_deductions','tax_factor_r','states','cities','cnae','hr_settings','import_settings','export_settings'] loop execute format('create policy public_read_active_%I on public.%I for select using (active = true)', table_name, table_name); execute format('create policy admin_manage_%I on public.%I for all using (public.is_admin()) with check (public.is_admin())', table_name, table_name); end loop; end $$;
create policy admin_manage_admin_roles on public.admin_roles for all using (public.is_admin()) with check (public.is_admin());
create policy admin_read_audit_logs on public.audit_logs for select using (public.is_admin());
create policy admin_insert_audit_logs on public.audit_logs for insert with check (public.is_admin());
create policy admin_read_config_versions on public.config_versions for select using (public.is_admin());
create policy admin_insert_config_versions on public.config_versions for insert with check (public.is_admin());

create or replace function public.create_config_version(p_module_key public.config_module, p_entity_key text, p_entity_id uuid, p_config jsonb, p_change_reason text, p_actor_id uuid) returns public.config_versions language plpgsql security definer set search_path = public as $$ declare next_version integer; inserted public.config_versions; target_table text; begin if not public.is_admin() then raise exception 'admin permission required'; end if; select coalesce(max(version),0)+1 into next_version from public.config_versions where module_key = p_module_key and entity_key = p_entity_key; insert into public.config_versions(module_key,entity_key,entity_id,config,change_reason,version,created_by,updated_by) values (p_module_key,p_entity_key,p_entity_id,p_config,p_change_reason,next_version,p_actor_id,p_actor_id) returning * into inserted; target_table := case p_module_key when 'general' then 'system_settings' when 'financial' then 'financial_settings' when 'tax' then 'tax_settings' when 'hr' then 'hr_settings' when 'import' then 'import_settings' when 'export' then 'export_settings' else null end; if target_table is not null then execute format('update public.%I set active = false where active = true', target_table); execute format('insert into public.%I (settings,version,created_by,updated_by) values ($1,$2,$3,$3)', target_table) using p_config,next_version,p_actor_id; end if; insert into public.audit_logs(actor_id,action,entity_table,entity_id,after_value,created_by,updated_by) values (p_actor_id,'config.version.created','config_versions',inserted.id,to_jsonb(inserted),p_actor_id,p_actor_id); return inserted; end; $$;
create or replace function public.rollback_config_version(p_version_id uuid, p_actor_id uuid, p_change_reason text) returns public.config_versions language plpgsql security definer set search_path = public as $$ declare source_version public.config_versions; begin if not public.is_admin() then raise exception 'admin permission required'; end if; select * into source_version from public.config_versions where id = p_version_id; if source_version.id is null then raise exception 'version not found'; end if; return public.create_config_version(source_version.module_key,source_version.entity_key,source_version.entity_id,source_version.config,p_change_reason,p_actor_id); end; $$;
